### ISSUE TITLE
Problem running algotrading

### ISSUE THREAD

**Issue by ghost** [panditanvita/BTCpredictor#6]
Hello! Thanks a lot for this program.

I can't figure why algotrading.m is running wrong. Here you have the new version I downloaded a few days ago.
![algotrading](https://user-images.githubusercontent.com/29773283/28994791-e7402506-79d6-11e7-9aa5-1015bda22bd2.png)

When I test the older version, I obtain this result, but nothing else happen.
![algotrading_old](https://user-images.githubusercontent.com/29773283/28994802-25eabeba-79d7-11e7-984f-2a3cf9c783f9.png)

Please help!

**Comment by panditanvita** [comment]
Looking at line 119 in algotrading.m - looks like the definition of numPoints got moved after the use of numPoints as an rvalue. I moved it back up, so that should be fixed now. I don't have MATLAB anymore so I can't run it myself and see.

Once it finishes running correctly, you should see a graph of trades, similar to what is shown in the README
